version: '3'

services:
  minio-s3:
    container_name: minio
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
#    ports:
#      - ${MINIO_PORT}:9000
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command:
      server /data
    volumes:
      - s3-disk:/data
    networks:
      - lradar
      - proxy-net


volumes:
  s3-disk:
    external:
      name: s3-disk

networks:
  lradar:
    internal: true
  proxy-net:
    external:
      name: proxy-net