version: '3'

services:
  jupyterhub:
    container_name: jupyterhub
    build: .
    networks:
      - lradar
      - proxy-net


networks:
  lradar:
    internal: true
  proxy-net:
    external:
      name: proxy-net
