version: '3'

services:
  semantic-search:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8501"
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
      - semantic
      - proxy-net


networks:
  semantic:
    internal: true
  proxy-net:
    external:
      name: proxy-net
