version: '3.1'
services:
    proxy:
        build: .
        volumes:
          - ./templates:/etc/nginx/templates
        environment:
          - LR_DEV=lr.dev.localhost
          - LR_PROD=lr.prod.localhost

        ports:
            - "80:80"

        networks:
            - proxy-net
networks:
  proxy-net:
    external:
      name: proxy-net
