version: '3.1'
services:
    proxy:
        build: .
        volumes:
          - ./templates:/etc/nginx/templates
        environment:
          - LR_DEV=lr.localhost
          - LR_PROD=lr.meaningfy.ws
          - SC_DEV=sc.localhost
          - SC_PROD=sc.meaningfy.ws

        ports:
            - "80:80"

        networks:
            - proxy-net
networks:
  proxy-net:
    external:
      name: proxy-net
