version: '3'

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - jupyter-notebook-work:/home/jovyan/work
    ports:
      - ${SFTP_PORT}:22
    #    command: ${SFTP_USER}:${SFTP_PASSWORD}:::upload
    #    command: ${SFTP_USER}:${SFTP_PASSWORD}:${SFTP_USER_ID}::upload
    command: jovyan:${SFTP_PASSWORD}:::work
    networks:
      - notebook

  notebook:
    image: notebook_meaningfy:latest
    build:
      context: .
    command: "start-notebook.sh \
            --NotebookApp.password=${JUPYTER_PASSWORD} \
            --NotebookApp.token=${JUPYTER_TOKEN}"
    volumes:
      - jupyter-notebook-work:/home/jovyan/work
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
    networks:
      - notebook
      - proxy-net

volumes:
  jupyter-notebook-work:

networks:
  notebook:
    internal: true
  proxy-net:
    external:
      name: proxy-net


